name: Greet user
on: push
jobs:
    greet:
          runs-on: ubuntu-latest
          steps:
                - name: Greet user
                  run: echo "Hellow world"
                - name: Bye user
                  run: echo "Bye bye !"